### PR TITLE
refactor(api-calls): readability and maintainability

### PR DESCRIPTION
**Pull request by JonathanXITASO**
# Description

Refactor all frontend-backend api calls and fetch from server side everywhere.

Fixes # (MNES-1223)

## Type of change

-   [x] Minor change (non-breaking change, e.g. documentation adaption)

# Checklist:

-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that prove my fix or my feature works
-   [ ] New and existing tests pass locally with my changes
-   [ ] My changes contain no console logs

### CODE REVIEW

**Comment by GailMelanie** [comment]
Since I wasn't involved in this whole refactoring: Does it make sense to write ADR(s) for the decisions you made?

**Comment by fleanegan** [comment]
> Since I wasn't involved in this whole refactoring: Does it make sense to write ADR(s) for the decisions you made?

I think this is a really good idea: An ADR to document that API-clients should return a Wrapper and only throw in unexpected cases

**Review by fleanegan — APPROVED** [review]
Only took a rough look, since already reviewed the merge into the feature branch. Looks ok to me

**Review by FranzXitaso — APPROVED** [review]
Same opinion: Since We already reviewied most of this in the preceeding PRs, I only skimmed this and it looks fine to me!

**Pull request merged**
